### ISSUE TITLE
Add position data to SlideChangeEvent 

### ISSUE THREAD

**Issue by paodb** [FlowingCode/CarouselAddon#10]
This comes from question on Vaadin Directory by Thomas Thiele asking how to get the index of the slide element in the change listener.

Position attribute will do this, but right now is not part of the SlideChangeEvent. In the client side the event has this value.

**Comment by CoderGarm** [comment]
Moin,

there is a small problem with the position variable because is is not set to the member variable from the constructor call in the 2.1.0 version of the slider.
Besides from that, I like the slider a lot :)

Best regards,
Karsten

**Comment by javier-godoy** [comment]
@CoderGarm Good catch! I created a separate issue for fixing it.

**Comment by CoderGarm** [comment]
Thanks a lot :)

I don't know if I should  open a dedicated ticket for another point I have found. It is about a not really useful combination of options for the carousel which creates a simple optical problem.

If the ```Carousel#withStartPosition```-method is used (only tested it with a parameter = 1) with a carousel which holds only a single slide, there will be two dots displayed in the navigation insteadt of one dot.

The use-case is not realistic but I used the example and this happens while making some experiments.

**Comment by paodb** [comment]
@CoderGarm It's really great that you're experimenting with our component! I will create a new ticket to investigate the escenario you mentioned. For the future, yes, it will be better if you just create a different ticket for each doubt or issue that you may found. 

Thanks.
