### ISSUE TITLE
Start position 1 & one slide show 2 dots

### ISSUE THREAD

**Issue by paodb** [FlowingCode/CarouselAddon#19]
This comes from #10 [comment](https://github.com/FlowingCode/CarouselAddon/issues/10#issuecomment-884289186).

If the Carousel#withStartPosition-method is used (only tested it with a parameter = 1) with a carousel which holds only a single slide, there will be two dots displayed in the navigation instead of one dot.

**Comment by paodb** [comment]
I wasn't able to reproduce this behavior. I did a simple test based on our current master:  

```java
    Slide s1 = new Slide(createSlideContent("Slide 1", "green"));
    Carousel c = new Carousel(s1);
    c.setWidth("100%");
    c.setHeight("180px");
    c.setStartPosition(1);
    add(c);
```
and it shows the only slide that was added and only one dot, like shown in the picture:

![image](https://user-images.githubusercontent.com/30666649/126707904-5e93dcc6-a6cd-4f7c-912e-c3d94f750ed7.png)

In fact, it doesn't matter if you chose a greater number to set in setStartPosition, it just displays one dot as there's only one slide.

**Comment by CoderGarm** [comment]
Hey,

I produced this issue in another setting:

```
member variable:
    Carousel c = new Carousel().withSlideDuration(4).withStartPosition(1);

constructor() {
    add(c);
}

addSlide(Sting title) {
    Slide s1 = new Slide(createSlideContent(title));
    c.setSlides(new Slide[]{s1};
}
```

The second dot occures at start and nothing is displayed: 
![slide1](https://user-images.githubusercontent.com/76734109/126769528-98df7eac-f36f-4753-a9ec-b5513dc09ef5.png)

If you use the slide-navigation the second dot disappears:
![slide2](https://user-images.githubusercontent.com/76734109/126769530-93aafcfc-0ae0-4daf-9c90-e57325cbd37c.png)

**Comment by paodb** [comment]
Hi @CoderGarm, sorry for the delay on this. Is this still an issue for you? In your latest example, no slides are being added to the carousel. I tried again as in https://github.com/FlowingCode/CarouselAddon/issues/19#issuecomment-885228049 but not able to reproduce the double dot display.

**Comment by CoderGarm** [comment]
Hey,

it's not an issue. I've switched my application from the vaadin frontend to angular completely a few month ago.
