### ISSUE TITLE
Carousel within vaadin-dialog has strange auto-progress behaviour

### ISSUE THREAD

**Issue by GrandyB** [FlowingCode/CarouselAddon#21]
In our application we are wanting to show a Carousel within a Dialog.

With auto-progress enabled on the Carousel, the example code with 1/2/3/4 slides ping-pongs from 1 -> 3 -> 1 -> 3 etc. Never goes to slides 2 or 4.

Setting startPosition to be the 2nd slide, it instead goes 2 -> 4 -> 2 -> 4 etc.

Example Dialog code to replicate would be... (borrowing s1 to s4 from the existing examples):
`add(new Button("Open", (e) -> new Dialog(new Carousel(s1,s2,s3,s4).withAutoProgress()).open()));`

**Comment by javier-godoy** [comment]
Confirmed with Vaadin 14.6.8 / Carousel 2.1.2-SNAPSHOT

**Comment by paodb** [comment]
I was able to reproduce the issue but still haven't been able to figure out what's causing that behavior.

**Comment by mlopezFC** [comment]
The problem is that [the function attached](https://github.com/Link2Twenty/l2t-paper-slider/blob/master/l2t-paper-slider.html#L585) is being called twice when inside the dialog.
I do not know right now how to avoid that. I'll keep investigating.

**Comment by Rlaxfax** [comment]
Hello,
is there any update to this bug?I am facing the same issue.

Thanks in advance.

**Comment by CrisVnait** [comment]
I also have the problem described above and hope that an update will come in the next time.

**Comment by paodb** [comment]
Fix released in Carousel version 2.1.4.
