### ISSUE TITLE
Dev mode - corousel not shown

### ISSUE THREAD

**Issue by hr015** [FlowingCode/CarouselAddon#22]
Hi,
I have trouble with this addon. It works fine when I deploy it for production (package -Pproduction), but when I use it in development mode with springboot, I do not see the carousel. Instead, I see all the slides together in a column.
Could you help me with this?
Thank you!

**Comment by paodb** [comment]
Hello @hr015, if you're using springboot make sure to add this value: **com.flowingcode.vaadin.addons** to the ```vaadin.whitelisted-packages``` property in your _application.properties_ file. More information about whitelisted configuration [here](https://vaadin.com/docs/latest/flow/integrations/spring/configuration/#special-configuration-parameters).
