### ISSUE TITLE
CI build failure for Vaadin 23 and 24

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/CarouselAddon#27]
After adding CI build checks for Vaadin 23 and 24 (588662e60ad910ed773d5546319dc5c619cd92b5, 86780519399007a8f7e0c259edbf91fa7b28a88e, 676ed672d83ba653cf1191d5c3828afd453eb8c5) I found that 23 and 24 builds fail because of the removal of `HtmlImport`, which is used here https://github.com/FlowingCode/CarouselAddon/blob/588662e60ad910ed773d5546319dc5c619cd92b5/src/main/java/com/flowingcode/vaadin/addons/carousel/Carousel.java#L36 

The add-on, however, **IS** compatible with Vaadin 23 and 24 because missing annotations do not throw any exception (see https://stackoverflow.com/q/3567413/1297272). We have demos at https://addonsv23.flowingcode.com/carousel and https://addonsv24.flowingcode.com/carousel

I think we should revert the mentioned commits, and keep CI for Vaadin 14 only.

**Comment by mlopezFC** [comment]
I agree. Let's do that. If we have issues later we can just remove the annotation and stop supporting Vaadin versions < 14
