### ISSUE TITLE
Swipe is not disabled even after setting disableSwipe to true 

### ISSUE THREAD

**Issue by Ranga-RV6464** [FlowingCode/CarouselAddon#29]
I have tried multiple properties for disabling the swipe but its not happening
 Carousel c = new Carousel(s1,s2);
c.setDisableSwipe(true);
c.setAttribute("disable-swipe", "true")

**Comment by paodb** [comment]
Hi, it seems that `c.setDisableSwipe(true);` is not working as expected. Please try
`c.getElement().setAttribute("disable-swipe", "true");` or `new Carousel(s1, s2).withoutSwipe();`
