### ISSUE TITLE
withoutNavigation method

### ISSUE THREAD

**Issue by bluegod777** [FlowingCode/CarouselAddon#36]
I am assuming that "withoutNavigation" means that the navigation circles should be hidden.

If so, shouldn't we call setHideNavigation with a parameter of 'true'?

The current code sets it to "false".

```
  public Carousel withoutNavigation() {
    this.setHideNavigation(false);
    return this;
  }
```

**Comment by javier-godoy** [comment]
Hello. Yes, according to the documentation at https://www.npmjs.com/package/@xpertsea/paper-slider it should hide the circles. Thanks for reporting this issue, we'll take a look.
